Ext.define('NAF.model.Activity', {
    extend: 'Ext.data.Model',
    idProperty: '_id',
    fields: [
        '_id',
        'attendee',
        'category_id',
        'contact',
        'contact_name',
        'contact_email',
        'contact_phone',
        'description',
        {name: 'dtstart', type:'date'},
        'dtstart-time',
        {name: 'dtend', type:'date'},
        'dtend-time',
        'own_vehicle',
        'price',
        'member_price',
        'free',
        'mva',
        'responsibility',
        'summary',
        'supervisor_included',
        'tags',
        'url',
        'vehicle',
        'video',
        'location_id',
        {name: 'location', mapping: 'location.name'},
        'address',
        'organizer_id',
        {name: 'organizer', mapping: 'organizer.name'},
        'active',
        'region',
        'age_from',
        'age_to',
        'political_contact',
        'response_result',
        'volunteers_involved_count',
        'volunteers_used_count',
        'competence_needs',
        'participants_count',
        'result',
        'potential_improvements',
        'media_title',
        'media_outlet',
        'media_url' ]

});